/**: 

  ros__parameters:

    solo_params: 
      name: ['grapple', 'avc']
      address: [7, 3]
      baudrate: [937500, 937500]
      pwm_frequency_khz: [20, 20]
      current_limit: [1, 2]
      motor_poles_counts: [4, 4]
      command_mode: [DIGITAL, DIGITAL]
      motor_type: [BLDC_PMSM, BLDC_PMSM]
      feedback_control_mode: [HALL_SENSORS, HALL_SENSORS]
      current_controller_kp: [1.2, 3.397499]
      current_controller_ki: [0.014, 0.0158462]
      speed_controller_kp: [0.2, 0.0099868]
      speed_controller_ki: [0.004, 0.0029907]
      position_controller_kp: [20.0, 2.0]
      position_controller_ki: [0.0, 0.0099868]
      control_mode: [POSITION_MODE, POSITION_MODE]
      speed_limit: [2500, 2000]
      speed_acceleration: [100, 100]
      speed_deceleration: [100, 100]
      logger_level: [0, 0]

    feedback_params:
      frequency: 10.0 # [Hz]

    state_machine_params:
      frequency: 10.0 # [Hz]